SET GLOBAL event_scheduler = ON;

CREATE EVENT IF NOT EXISTS `auto_delete_old_UUID_references`
ON SCHEDULE EVERY 1 DAY
STARTS (TIMESTAMP(CURRENT_DATE, '00:00:00'))
DO
DELETE FROM UUID_reference WHERE created_at < DATE_SUB(NOW(), INTERVAL 30 DAY);
